# Generated by Django 6.0.2 on 2026-02-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_name', models.CharField(max_length=30)),
                ('task_start_date', models.DateField()),
                ('task_end_date', models.DateField()),
            ],
        ),
    ]
